version: '3.8'

services:
  pets-yu:
    build: .
    container_name: pets-yu-web
    ports:
      - "8090:80"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
