version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: pets-yu-db
    environment:
      POSTGRES_DB: petsyu_db
      POSTGRES_USER: petsyu
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U petsyu -d petsyu_db"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - pets-yu-network

  # Backend API
  backend:
    image: node:20-bullseye-slim
    container_name: pets-yu-api
    working_dir: /app
    environment:
      DATABASE_URL: "postgresql://petsyu:${POSTGRES_PASSWORD:-password}@postgres:5432/petsyu_db?schema=public"
      JWT_SECRET: ${JWT_SECRET:-your-super-secret-jwt-key-change-this-in-production}
      JWT_EXPIRES_IN: "7d"
      PORT: 3001
      NODE_ENV: "production"
      FRONTEND_URL: "${FRONTEND_URL:-http://localhost:8090}"
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - backend_logs:/app/logs
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - pets-yu-network
    command: >
      sh -c "
        apt-get update &&
        apt-get install -y python3 make g++ openssl ca-certificates wget &&
        npm ci &&
        npx prisma generate &&
        npm run build &&
        npm start
      "
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Frontend
  frontend:
    image: node:20-bullseye-slim
    container_name: pets-yu-web
    working_dir: /app
    environment:
      VITE_API_URL: "${API_URL:-http://localhost:3001/api}"
    ports:
      - "8090:3000"
    volumes:
      - .:/app
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - pets-yu-network
    command: >
      sh -c "
        npm ci &&
        npm run build &&
        npm run preview -- --host 0.0.0.0 --port 3000
      "
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  postgres_data:
    driver: local
  backend_logs:
    driver: local

networks:
  pets-yu-network:
    driver: bridge
