version: '3.8'

services:
  # PostgreSQL Database - usando imagen que debería estar disponible
  postgres:
    image: postgres:15-alpine
    container_name: pets-yu-db
    environment:
      POSTGRES_DB: petsyu_db
      POSTGRES_USER: petsyu
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - pets-yu-network

  # Nginx - usando imagen que debería estar disponible
  nginx:
    image: nginx:1.25-alpine
    container_name: pets-yu-nginx
    ports:
      - "80:80"
      - "8090:80"
    volumes:
      - ./dist:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped
    networks:
      - pets-yu-network

volumes:
  postgres_data:
    driver: local

networks:
  pets-yu-network:
    driver: bridge